services:
  - type: web
    name: open-deep-research
    env: node
    buildCommand: |
      npm i -g pnpm
      pnpm install
      pnpm db:migrate
      pnpm build
    startCommand: PORT=3000 pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: POSTGRES_URL
        fromDatabase:
          name: open-deep-research-db
          property: connectionString
      - key: BYPASS_JSON_VALIDATION
        value: "false"
      - key: NEXTAUTH_URL
         value: "https://open-deep-research-rl8o.onrender.com"
      - key: NEXTAUTH_URL_INTERNAL
         value: "https://open-deep-research-rl8o.onrender.com"
      - key: RENDER_EXTERNAL_URL
         value: "https://open-deep-research-rl8o.onrender.com"
      - key: NEXTAUTH_SECRET
         sync: false
    port: 3000

databases:
  - name: open-deep-research-db
    databaseName: open_deep_research
    plan: free
    ipAllowList: []