services:
  - type: web
    name: open-deep-research
    env: node
    region: frankfurt
    buildCommand: |
      echo "Node version: $(node -v)"
      npm i -g pnpm
      pnpm install
      pnpm db:migrate
      pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: BYPASS_JSON_VALIDATION
        value: "false"
      - key: POSTGRES_URL
        fromDatabase:
          name: open-deep-research-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: open-deep-research-db
    databaseName: open_deep_research
    plan: free
    ipAllowList: []